global_seed: 42

model_params:
  depth_model_params:
    input_channels_image: 3 
    input_channels_depth: 2 

    min_pool_sizes_sparse_to_dense_pool: [5, 7, 9, 11, 13]
    max_pool_sizes_sparse_to_dense_pool: [15, 17]
    n_convolution_sparse_to_dense_pool: 3  
    n_filter_sparse_to_dense_pool: 8 

    n_filters_encoder_image: [48, 96, 192, 384, 384] 
    n_filters_encoder_depth: [16, 32, 64, 128, 128]
    n_filters_decoder: [256, 128, 128, 64, 12] 
    resolutions_backprojection: [0, 1, 2, 3]
    deconv_type: 'up'
    weight_initializer: 'xavier_normal'
    activation_func: 'leaky_relu'
    min_predict_depth: 1.5
    max_predict_depth: 100.0

  pose_net_params:
    encoder_type: 'resnet18'
    rotation_parameterization: 'axis'
    weight_initializer: 'xavier_normal'
    activation_func: 'relu'
  
  outlier_params:
      kernel_size: 7 
      threshold: 1.5 


# Training settings
train_params:
  n_batch: 25
  n_height: 256
  n_width: 1216
  n_thread: 48
  device: 'gpu'
  lr_depth: 2.0e-4
  lr_pose: 2.0e-4
  # learning_rates: [0.5e-4, 1.0e-4, 1.5e-4, 1.0e-4, 5.0e-5, 2.0e-5] # 对应epoch
  learning_schedule: [2, 30, 45, 60]

  loss_weights:
    # Loss function settings
    w_color: 0.15 
    w_structure: 0.95 
    w_sparse_depth: 0.60 
    w_smoothness: 0.0400 
    w_weight_decay_depth: 0.00 
    w_weight_decay_pose: 0.00 

  output_dir: 'trained_kbnet/kitti'
  n_checkpoint: 5000
  n_summary: 5000 
  n_summary_display: 4
  validation_start_step: 100000
  restore_path: null

  augmentation_probabilities: [1.00, 0.50, 0.25]
  augmentation_schedule: [50, 55, 60]
  aug_params:
    # normalized_image_range: [0, 1]
    random_flip_type: []
    random_remove_points: [0.60, 0.70]  # how much to remove from each sample
    random_noise_type: []
    random_noise_spread: -1


dataset_train_params:
  shape: [256, 1216, 3]
  RandCrop: true

  train_image_path: 'training/kitti/kitti_train_image-clean.txt'
  train_sparse_depth_path: 'training/kitti/kitti_train_sparse_depth-clean.txt' 
  train_intrinsics_path: 'training/kitti/kitti_train_intrinsics-clean.txt' 


dataset_val_params:
  val_file_path: 'validation/val_file_path.json'

  min_evaluate_depth: 0.0 
  max_evaluate_depth: 100.0 


pretrained_weights:
  model_path: '/media/data2/libihan/codes/calibrated-backprojection-network/trained_kbnet/kitti/2024-10-12T18-05-52/checkpoints/ckpt_iter_10000.pth'