global_seed: 42

model_params:
  output_params:
    min_predict_depth: 1.5
    max_predict_depth: 100.0

  depth_anything:
    encoder: 'vitb' # choices=['vits', 'vitb', 'vitl', 'vitg']
    input_size: 518

  scale_model_params:
    use_prefill: true

  outlier_params:
      kernel_size: 7 
      threshold: 1.5 


# Training settings
train_params:
  n_batch: 1
  n_height: 256
  n_width: 1216
  n_thread: 24
  device: 'gpu'
  lr_scale: 2.0e-4
  # learning_rates: [0.5e-4, 1.0e-4, 1.5e-4, 1.0e-4, 0.5e-4, 0.2e-4] # 对应epoch
  # learning_schedule: [2, 8, 20, 30, 45, 60]
  learning_schedule: [2, 30, 45, 60]

  patch_size: 14

  loss_weights:
    # Loss function settings
    w_gt: 1
    w_e: 0.2 

  output_dir: 'trained_kbnet/kitti'
  n_checkpoint: 1000
  n_summary: 1000
  n_summary_display: 4
  n_test: 1000
  validation_start_step: 100000
  restore_path: null

  augmentation_probabilities: [1.00, 0.50, 0.25]
  augmentation_schedule: [50, 55, 60]
  aug_params:
    # normalized_image_range: [0, 1]
    random_flip_type: []
    random_remove_points: [0.60, 0.70]  # how much to remove from each sample
    random_noise_type: []
    random_noise_spread: -1
  
  # 分布式训练相关配置
  mixed_precision_training: 'no'
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0


dataset_train_params:
  shape: [256, 1216, 3]
  RandCrop: false
  train_file_path : 'configs/kitti_reldepth.json'


dataset_val_params:
  val_file_path: 'configs/kitti_reldepth.json'

  min_evaluate_depth: 0.0 
  max_evaluate_depth: 100.0 


pretrained_weights:
  model_path:
  depth_anything_ckpt: '/media/data2/libihan/codes/Depth-Anything-V2/checkpoints/depth_anything_v2_vitb.pth'