train_stage: 1

output_dir: "outputs"

# 训练数据配置
dataset_params:
  root_dir: '/mnt/nas/tonghua/codes/LiveAIHead/data/vfhq/'
  frame_shape: [256, 256, 3]
  id_sampling: False
  pairs_list: None
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: False
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      hue: 0.1
      saturation: 0.1
      

# 预训练权重
pretrained_weights:
    appearance_feature_extractor: pretrained_weights/liveportrait/base_models/appearance_feature_extractor.pth
    motion_extractor: pretrained_weights/liveportrait/base_models/motion_extractor.pth
    warping_module: pretrained_weights/liveportrait/base_models/warping_module.pth
    spade_generator: pretrained_weights/liveportrait/base_models/spade_generator.pth
    # todo: stage2 training
    stitching_retargeting_module: pretrained_weights/liveportrait/retargeting_models/stitching_retargeting_module.pth


# 训练参数配置
train_params:
  num_epochs: 300
  num_repeats: 75
  epoch_milestones: [180,]
  lr_generator: 2.0e-4
  lr_motion_extractor: 2.0e-4
  lr_appearance_feature_extractor: 2.0e-4
  lr_warping_module: 2.0e-4
  lr_discriminator: 2.0e-4
  lr_discriminator_face: 2.0e-4
  lr_discriminator_lip: 2.0e-4
  gan_mode: 'hinge'    # hinge or ls
  batch_size: 3
  num_workers: 8
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 10
  hopenet_snapshot: 'pretrained_weights/hopenet_robust_alpha1.pkl'
  resnet50: 'pretrained_weights/backbone.pth'
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan: 1
    generator_gan_face: 1
    generator_gan_lip: 1
    discriminator_gan: 1
    discriminator_gan_face: 1
    discriminator_gan_lip: 1
    feature_matching: [10, 10, 10, 10]
    feature_matching_face: [10, 10, 10, 10]
    feature_matching_lip: [10, 10, 10, 10]
    perceptual: [10, 10, 10, 10, 10]
    equivariance_value: 10
    equivariance_jacobian: 0    # 10
    keypoint: 10
    headpose: 20
    expression: 5
    guide: 3  # 需要测量修改
    face_id: 5  # 需要测量修改

  # 分布式训练相关配置
  mixed_precision_training: 'no'
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0

# 判别器参数配置
discriminator_params:
  scales: [1]
  num_channels: 3
  block_expansion: 32
  max_features: 512
  num_blocks: 4
  sn: True

discriminator_face_params:
  scales: [1]
  num_channels: 3
  block_expansion: 32
  max_features: 512
  num_blocks: 4
  sn: True

discriminator_lip_params:
  scales: [1]
  num_channels: 3
  block_expansion: 32
  max_features: 512
  num_blocks: 4
  sn: True


eval_and_save_freq: 10000
global_seed: 42

is_debug: false
